version: "3.9"

services:
  frontend:
    build: "./frontend"
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/:/app
  backend:
    build: "./backend"
    command: uvicorn src.api:app --reload --port 8008 --host 0.0.0.0
    ports:
      - "8008:8008"
    volumes:
      - ./backend/:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
