version: "3.9"

services:
  frontend:
    build: "./frontend"
    env_file: dev.env
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/:/app
  backend:
    build: "./backend"
    env_file: dev.env
    command: uvicorn src.api:app --reload --port 8008 --host 0.0.0.0
    ports:
      - "8008:8008"
    volumes:
      - ./backend/:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./data/mongo:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017
